<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Mustafa\YalidineDelivery\Block\Adminhtml\Authentication\TestAuthentication */ ?>
<script type="text/javascript">
require([
    'jquery',
    'prototype',
    'mage/backend/validation',
    'jquery/validate'
], function(jQuery){
    jQuery('#yalidine_authentication_test').click(function () {
        var lien = window.location.pathname.split('/');
        var storeid=0;
        if(lien.indexOf('store') !== -1){
            storeid= lien[lien.indexOf('store')+1];
        
            let data = {};
            if(jQuery('#carriers_yalidine_user').length === 1 && jQuery('#carriers_yalidine_key').length === 1){
                data = {
                  'userId' : jQuery('#carriers_yalidine_user').val(),
                  'apiKey' : jQuery('#carriers_yalidine_key').val(),
                  'storeId' : storeid
                };
            } else {
                data = {
                  'userId': '',
                  'apiKey' : '',
                  'storeId' : storeid
                }
            }
            jQuery.ajax({
                url: "<?php echo $block->getAjaxUrl(); ?>",
                type: 'post',
                dataType: 'json',
                data: data,
                showLoader: true,
            }).done(function(returnData){
                  // Replace OrganizationID
                if (returnData.status == 'success') {
                  // Autenticaton Succesfull

                  jQuery('#yalidine_authentication_test').removeClass('error').addClass('success');
                } else {
                  // Failed
                  jQuery('#yalidine_authentication_test').removeClass('success').addClass('error');

                }

                jQuery('#row_carriers_yalidine_test_authentication p.note span').text(returnData.message);
            });
        
        } else {
            jQuery('#yalidine_authentication_test').removeClass('success').addClass('error');
            jQuery('#row_carriers_yalidine_test_authentication p.note span').text('Please choose a store');
        }
    })
});
</script>

<?= $block->getButtonHtml() ?>